almacen/almacen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url="login/", permanent=False)),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')), # incluyendo el archivo urls de la aplicación producto
]

almacen/core/urls.py
from django.urls import path

from .views import CustomLoginView, CustomLogoutView, RegistroUsuarioCreateView, pagina_home

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name="login"),
    path('logout/', CustomLogoutView.as_view(), name="logout"),
    path('register/', RegistroUsuarioCreateView.as_view(), name="register"),
    path('home/', pagina_home, name='home')
]

almacen/productos/urls.py
from django.urls import path
# importando las vistas
from .views import (
    CategoriaListView,
    CategoriaCreateView,
    # proveedores
    ProveedorListView,
    ProveedorCreateView,
    # productos
    ProductoListView,
    ProductoCreateView,
    ProductoUpdateView,
    ProductoDeleteView,
    ProductoDetailView
)

# agregar un identificador de enrutamiento
app_name = "productos"

# enrutamiento
urlpatterns = [
    path('categorias/', CategoriaListView.as_view(), name="categoria-list"),
    path('categorias/nueva', CategoriaCreateView.as_view(), name="categoria-create"),
    # proveedores
    path('proveedores/', ProveedorListView.as_view(), name="proveedor-list"),
    path('proveedores/nuevo', ProveedorCreateView.as_view(), name="proveedor-create"),
    # productos
    path('', ProductoListView.as_view(), name="producto-list"),
    path('<int:pk>', ProductoDetailView.as_view(), name="producto-detail"),
    path('nuevo/', ProductoCreateView.as_view(), name="producto-create"),    
    path('editar/<int:pk>', ProductoUpdateView.as_view(), name="producto-update"),    
    path('eliminar/<int:pk>', ProductoDeleteView.as_view(), name="producto-delete")
]

almacen/productos/models.py
from django.db import models

# Create your models here.

# modelo categoria
class Categoria(models.Model):

    # atributos
    nombre = models.CharField(max_length=50, unique=True) # nombre varchar(50) unique = true not null
    descripcion = models.TextField(max_length=255, null=True, blank=True) 

    # ajustes a las tablas y modelos => 's o => oes
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ["nombre"]

    # polimorfismo
    def __str__(self):
        return f"{self.nombre}"

# modelo proveedor
class Proveedor(models.Model):

    # atributos
    nombre = models.CharField(max_length=50) # nombre varchar(50) unique = true not null
    telefono = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True) 
    direccion = models.TextField(max_length=255, null=True, blank=True)
    contacto = models.CharField(max_length=100, null=True, blank=True)

    # ajustes a las tablas y modelos => 's o => oes
    class Meta:
        verbose_name = "Proveedor"
        verbose_name_plural = "Proveedores"
        ordering = ["nombre"]

    # polimorfismo
    def __str__(self):
        return f"{self.nombre}"

# importar la clase Model de models.
# create table Producto()
class Producto(models.Model): # aplicando herencia
    # (el id Django lo genera de manera automatica)
    # crear los atributos

    nombre = models.CharField(max_length=50) # nombre varchar(50) not null
    descripcion = models.TextField(null=True, max_length=150) # descripcion varchar(150)
    precio_compra = models.DecimalField(max_digits=12, decimal_places=2) # precio decimal(12,2) not null
    precio_venta = models.DecimalField(max_digits=12, decimal_places=2)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)


    # ajustes a las tablas y modelos => 's o => oes
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ["nombre"]

    # crear un metodo
    def __str__(self): # polimorfismo
        return f"{self.nombre} - {self.stock} unidades"

almacen/productos/forms.py
# importar formularios de django
from django import forms
# importar los modelos
from .models import Categoria, Proveedor, Producto

# crear un formulario personalizado
class CategoriaForm(forms.ModelForm):
    
    # personalizar el formulario
    class Meta:
        model = Categoria
        # campos
        fields = ["nombre", "descripcion"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre Categoria"}),
            "descripcion": forms.Textarea(attrs={"class": "form-control", "placeholder": "Descripción Categoria", "rows": 3})
        }
        
        
class ProveedorForm(forms.ModelForm):
    
    class Meta:
        model = Proveedor
        # campos
        fields = ["nombre", "telefono", "email", "direccion", "contacto"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre Proveedor"}),
            "telefono": forms.TextInput(attrs={"class": "form-control", "placeholder": "Numero Telefono", "type": "tel"}),
            "email": forms.TextInput(attrs={"class": "form-control", "placeholder": "Correo Electronico", "type": "email"}),
            "direccion": forms.Textarea(attrs={"class": "form-control", "placeholder": "Dirección Proveedor", "rows": 3}),
            "contacto": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre Contacto"}),
        }

# crear un formulario personalizado para el producto
class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ["nombre","descripcion","precio_compra","precio_venta","categoria","proveedor","activo"]
        widgets = {
            "nombre": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Nombre Producto"}
            ),
            "descripcion": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Descripción Producto", "style": "height: 100px"}
            ),
            "precio_compra": forms.NumberInput(
                attrs={"class": "form-control", "step": "0.01"}
            ),
            "precio_venta": forms.NumberInput(
                attrs={"class": "form-control", "step": "0.01"}
            ),
            "categoria": forms.Select(
                attrs={"class":"form-select"}
            ),
            "proveedor": forms.Select(
                attrs={"class":"form-select"}
            ),
            "activo": forms.CheckboxInput(
                attrs={"class": "form-check-input", "placeholder": "Nombre Producto"}
            ),
        }

almacen/productos/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Categoria, Proveedor, Producto
# importar reverse_lazy de urls para redireccionar la respuesta a un formulario
from django.urls import reverse_lazy
# importar los formularios personalizados
from .forms import CategoriaForm, ProveedorForm, ProductoForm
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

# crear vistas genericas para categoria
class CategoriaListView(LoginRequiredMixin, ListView):

    # indicar cual es el modelo base
    model = Categoria
    fields = ["nombre", "descripcion"]
    template_name = "categorias/categoria-list.html"
    context_object_name = "categorias"
    
    
# crear una vista generica para agregar una categoria
class CategoriaCreateView(LoginRequiredMixin, CreateView):
    
    # indicar cual es el modelo base
    model = Categoria
    form_class = CategoriaForm
    # plantilla donde se va a renderizar el formulario
    template_name = "categorias/categoria-form.html"
    success_url = reverse_lazy("productos:categoria-list")
    
    
# Proveedores
class ProveedorListView(LoginRequiredMixin, ListView):
    
    model = Proveedor
    fields = ["nombre", "telefono", "contacto"]
    template_name = "proveedores/proveedor-list.html"
    context_object_name = "proveedores"
    
    
class ProveedorCreateView(LoginRequiredMixin, CreateView):
    
    model = Proveedor
    form_class = ProveedorForm
    template_name = "proveedores/proveedor-form.html"
    success_url = reverse_lazy("productos:proveedor-list")


# Productos

class ProductoListView(LoginRequiredMixin, ListView):

    model = Producto
    template_name = "productos/producto-list.html"
    context_object_name = "productos"

class ProductoCreateView(LoginRequiredMixin, CreateView):

    model = Producto
    form_class = ProductoForm
    template_name = "productos/producto-form.html"
    success_url = reverse_lazy("productos:producto-list")


class ProductoUpdateView(LoginRequiredMixin, UpdateView):

    model = Producto
    form_class = ProductoForm
    template_name = "productos/producto-form.html"
    success_url = reverse_lazy("productos:producto-list")


class ProductoDeleteView(LoginRequiredMixin, DeleteView):
    
    model = Producto
    template_name = "productos/producto-confirm.html"
    success_url = reverse_lazy("productos:producto-list")
    
    # polimorfismo
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto["titulo"] = f"Eliminar producto: {self.object.nombre}"
        return contexto
    

class ProductoDetailView(LoginRequiredMixin, DetailView):
    
    model = Producto
    template_name = "productos/producto-detail.html"
    context_object_name = "producto"

almacen/productos/templates/productos/producto-confirm.html
{% extends "core/base.html" %}

{% block title %}Eliminar Producto{% endblock %}

{% block contenido %}
<div class="card shadow-lg border-danger">
    <div class="card-header bg-danger text-white">
        <h3 class="text-center mb-0">{{ titulo }}</h3>
    </div>
    <div class="card-body text-center">
        <p class="fs-5">¿Estás seguro de que deseas eliminar el producto <strong>{{ object.nombre }}</strong>?</p>
        <p class="text-muted">Esta acción no se puede deshacer.</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger px-4">🗑️ Confirmar eliminación</button>
            <a href="{% url 'productos:producto-list' %}" class="btn btn-secondary px-4">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

almacen/productos/templates/productos/producto-detail.html
{% extends "core/base.html" %}

{% block title %}Detalle de Producto{% endblock %}

{% block contenido %}
<div class="card">
  <div class="card-header">
    <h2 class="text-center card-title">Detalle del Producto</h2>
  </div>
  <div class="card-body">
    <p><strong>Nombre:</strong> {{ producto.nombre }}</p>
    <p><strong>Descripción:</strong> {{ producto.descripcion }}</p>
    <p><strong>Categoría:</strong> {{ producto.categoria }}</p>
    <p><strong>Proveedor:</strong> {{ producto.proveedor }}</p>
    <p><strong>Precio de compra:</strong> ${{ producto.precio_compra }}</p>
    <p><strong>Precio de venta:</strong> ${{ producto.precio_venta }}</p>
    <p><strong>Activo:</strong> {{ producto.activo }}</p>
    <hr>
    <!-- <h3 class="card-subtitle">Inventario</h3>
    {% if producto.inventario_set.all %}
    <ul>
      {% for inv in producto.inventario_set.all %}
      <li>
        {{ inv.sucursal.nombre }} — Stock: {{ inv.stock }} (Mínimo: {{ inv.stock_minimo }})
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>Este producto no tiene inventario registrado.</p>
    {% endif %} -->
  </div>
  <div class="card-footer text-center">
    <a class="btn btn-outline-info" href="{% url 'productos:producto-list' %}">Volver al listado</a>
    {% if user.username == "admin" %}
    <a href="{% url 'productos:producto-update' producto.id %}" class="btn btn-outline-warning">Editar</a>
    <a href="{% url 'productos:producto-delete' producto.id %}" class="btn btn-outline-danger">Eliminar</a>
    {% else %}
    <a href="{% url 'productos:producto-update' producto.id %}" class="btn btn-outline-warning">Editar</a>
    {% endif%}
  </div>
</div>
{% endblock %}

almacen/productos/templates/productos/producto-form.html
{% extends "core/base.html" %}
<!-- agregar titulo si es edición o creación -->
{% block titulo %} 
    {% if form.instance.pk %} 
        Editar Producto
    {% else %}
        Nuevo Producto 
    {% endif %}
{% endblock %}


{% block contenido %}
<form method="post">
    {% csrf_token %}
    <div class="card shadow-lg">
        <div class="card-header">
            <h2 class="card-title text-center">
                 {% if form.instance.pk %} 
                    Editar Producto
                {% else %}
                    Nuevo Producto 
                {% endif %}
            </h2>
        </div>
        <div class="card-body">
            <div class="row mb-3">
                <div class="col">
                    <div class="form-floating mb-3">
                        {{ form.nombre }}
                        {{ form.nombre.label_tag }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        {{ form.descripcion }}
                        {{ form.descripcion.label_tag }}
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <div class="form-floating mb-3">
                        {{ form.precio_compra }}
                        {{ form.precio_compra.label_tag }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        {{ form.precio_venta }}
                        {{ form.precio_venta.label_tag }}
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col">
                    <div class="form-floating mb-3">
                        {{ form.categoria }}
                        {{ form.categoria.label_tag }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        {{ form.proveedor }}
                        {{ form.proveedor.label_tag }}
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col">
                    <div class="form-check">
                        {{ form.activo }}
                        {{ form.activo.label_tag }}
                    </div>
                </div>
            </div>

        </div>
        <div class="card-footer d-flex justify-content-evenly">
            <button type="submit" class="btn btn-success">Guardar</button>
            <a href="{% url 'productos:producto-list' %}" class="btn btn-outline-info">Cancelar</a>
        </div>
    </div>
</form>
{% endblock %}

almacen/productos/templates/productos/producto-list.html
{% extends "core/base.html" %}
{% load user_groups %}

{% block titulo %} Listado de Productos {% endblock %}

{% block contenido %}
<h1 class="text-center">Listado de Productos</h1>
<a href="{% url 'productos:producto-create' %}" class="btn btn-outline-success">Nuevo Producto</a>
<hr>
<table class="table table-bordered table-striped text-center">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Código</th>
      <th scope="col">Nombre</th>
      <th scope="col">Precio</th>
      <th scope="col">Activo</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for p in productos %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ p.id }}</td>
      <td>{{ p.nombre }}</td>
      <td>${{ p.precio_venta|floatformat:2 }}</td>
      <td>{{ p.activo }}</td>
      <td>
        {% if user.is_authenticated %}
          {% if user|has_group:"Administrador" %}
            <a href="{% url 'productos:producto-detail' p.id %}" class="btn btn-outline-info">Detalle</a>
            <a href="{% url 'productos:producto-update' p.id %}" class="btn btn-outline-warning">Editar</a>
            <a href="{% url 'productos:producto-delete' p.id %}" class="btn btn-outline-danger">Eliminar</a>
          {% elif user|has_group:"Inventario" %}
            <a href="{% url 'productos:producto-detail' p.id %}" class="btn btn-outline-info">Detalle</a>
            <a href="{% url 'productos:producto-update' p.id %}" class="btn btn-outline-warning">Editar</a>
          {% else %}
            <p>No estas autorizado</p>
          {% endif%}
        {% else %}
          <p>No estas autorizado</p>
        {% endif %}      
        
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}